#!/usr/bin/env bash

set -e

echo
echo "Installing gems locally"
echo "= = ="
echo

rubyAPIVersion=$(ruby -rrbconfig -e "puts RbConfig::CONFIG['ruby_version']")

if [ -d gems ]; then
  rm -rf gems

  echo "Removed previously installed gems"
  echo
fi

gemName=$(ls *.gemspec | sed -e 's/\.gemspec//' | grep $(basename $(realpath .) | sed -e 's/-/[-_]/g'))

echo "Gemspec: $gemName.gemspsec"

gemInfo=($(
  gem build $gemName.gemspec --output install-gems-installation.gem --quiet 2>/dev/null |
    sed -E -n 's/^[[:blank:]]*(Name|Version):[[:blank:]]*(.*)$/\2/p'
))
gem="${gemInfo[0]}-${gemInfo[1]}"

echo "Gem: $gem"
echo

cmd="gem install --no-document --install-dir ./gems/ruby/$rubyAPIVersion --no-user-install --development install-gems-installation.gem"

echo $cmd
($cmd)

echo

rm -vf install-gems-installation.gem

ruby <<RUBY > ./gems/gems_init.rb
puts "# Generated by $0\n\n"
Dir['gems/ruby/$rubyAPIVersion/gems/*'].each do |dir|
  dir = File.basename(dir)
  next if dir == "$gem"
  puts "\$LOAD_PATH.push(File.join(__dir__, 'ruby', '$rubyAPIVersion', 'gems', '#{dir}', 'lib'))"
end
RUBY

echo
echo "Wrote ./gems/gems_init.rb"

echo
echo "(done)"
echo "- - -"
echo
